
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author mario
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDialog();
        modificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EliminarAuto = new javax.swing.JButton();
        MostrarAuto = new javax.swing.JButton();
        AgregarAuto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        agregar = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        marca = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        modelo = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        precio = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        color = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        origen = new javax.swing.JTextPane();
        regresar = new javax.swing.JButton();
        tunear = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        marca1 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        modelo1 = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        precio1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        color1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        origen1 = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        buscar2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        car = new javax.swing.JTextArea();
        mostrar = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        mos = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        eliminar = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        buscar1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        mos1 = new javax.swing.JTextArea();
        bus = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        secion = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        contra = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        menuUsuario = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cmp = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        mt = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CrearCuenta = new javax.swing.JButton();
        IniciarSesionAdmin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        usuario = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        contraseña = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        correo = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        residencia = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        nacimiento = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        veriUsua = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        veriContra = new javax.swing.JTextPane();
        jButton8 = new javax.swing.JButton();

        menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar.setForeground(new java.awt.Color(0, 0, 0));
        modificar.setText("Modificar ");
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        menu.getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, 40));

        jLabel11.setFont(new java.awt.Font("Sitka Heading", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Need For Speed");
        menu.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 340, 60));

        EliminarAuto.setForeground(new java.awt.Color(0, 0, 0));
        EliminarAuto.setText("Eliminar Auto");
        EliminarAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarAutoMouseClicked(evt);
            }
        });
        EliminarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAutoActionPerformed(evt);
            }
        });
        menu.getContentPane().add(EliminarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 140, 40));

        MostrarAuto.setForeground(new java.awt.Color(0, 0, 0));
        MostrarAuto.setText("Mostrar Autos");
        MostrarAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarAutoMouseClicked(evt);
            }
        });
        menu.getContentPane().add(MostrarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, 40));

        AgregarAuto.setForeground(new java.awt.Color(0, 0, 0));
        AgregarAuto.setText("Agregar Auto");
        AgregarAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarAutoMouseClicked(evt);
            }
        });
        AgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAutoActionPerformed(evt);
            }
        });
        menu.getContentPane().add(AgregarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, 40));
        menu.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 20, 20));

        jButton13.setText("regresar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        menu.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Agregar Auto");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Marca:");

        jScrollPane8.setViewportView(marca);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Modelo:");

        jScrollPane9.setViewportView(modelo);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Color:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Precio:");

        jScrollPane10.setViewportView(precio);

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("CREAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        color.setForeground(new java.awt.Color(0, 0, 0));
        color.setText("colores");
        color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorMouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pais de Origen:");

        jScrollPane11.setViewportView(origen);

        regresar.setText("volver");
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar.getContentPane());
        agregar.getContentPane().setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                        .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel15)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButton1))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13))
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                        .addComponent(regresar)
                        .addGap(25, 25, 25))))
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(color))
                        .addGap(17, 17, 17)
                        .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(agregarLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel13))
                    .addGroup(agregarLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(regresar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tunear.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Modificar Auto");
        tunear.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 240, 80));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Marca:");
        tunear.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 50, 20));

        jScrollPane12.setViewportView(marca1);

        tunear.getContentPane().add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Modelo:");
        tunear.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jScrollPane13.setViewportView(modelo1);

        tunear.getContentPane().add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 170, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Color:");
        tunear.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Precio:");
        tunear.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jScrollPane14.setViewportView(precio1);

        tunear.getContentPane().add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 170, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Modificar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        tunear.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        color1.setForeground(new java.awt.Color(0, 0, 0));
        color1.setText("colores");
        color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color1MouseClicked(evt);
            }
        });
        tunear.getContentPane().add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 170, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Pais de Origen:");
        tunear.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jScrollPane15.setViewportView(origen1);

        tunear.getContentPane().add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 170, -1));

        jLabel23.setText(".");
        tunear.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 415, -1, -1));

        jButton3.setText("volver");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        tunear.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("buscar Auto por modelo");
        tunear.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        tunear.getContentPane().add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, -1));

        jButton4.setText("buscar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        tunear.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        car.setColumns(20);
        car.setRows(5);
        jScrollPane18.setViewportView(car);

        tunear.getContentPane().add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 130));

        mostrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Buscar modelo");
        mostrar.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
        mostrar.getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, -1));

        mos.setColumns(20);
        mos.setRows(5);
        jScrollPane16.setViewportView(mos);

        mostrar.getContentPane().add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, 140));

        jButton5.setText("buscar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        mostrar.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jButton6.setText("regresar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        mostrar.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        jLabel25.setText("Buscar modelo");

        jButton7.setText("eliminar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        mos1.setColumns(20);
        mos1.setRows(5);
        jScrollPane17.setViewportView(mos1);

        bus.setText("buscar");
        bus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busMouseClicked(evt);
            }
        });

        jButton9.setText("regresar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar.getContentPane());
        eliminar.getContentPane().setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(bus))
                    .addGroup(eliminarLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(265, 265, 265))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(32, 32, 32))))
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton7)
                .addGap(38, 38, 38)
                .addComponent(jButton9)
                .addGap(19, 19, 19))
        );

        jLabel27.setText("Contraseña");

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        jButton10.setText("Ingresar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout secionLayout = new javax.swing.GroupLayout(secion.getContentPane());
        secion.getContentPane().setLayout(secionLayout);
        secionLayout.setHorizontalGroup(
            secionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secionLayout.createSequentialGroup()
                .addGroup(secionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secionLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel27))
                    .addGroup(secionLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(secionLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton10)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        secionLayout.setVerticalGroup(
            secionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secionLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton10)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        menuUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Comprar Autos");
        menuUsuario.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Buscar por modelo");
        menuUsuario.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
        menuUsuario.getContentPane().add(cmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, 30));

        jButton11.setText("Buscar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        menuUsuario.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        mt.setColumns(20);
        mt.setRows(5);
        jScrollPane19.setViewportView(mt);

        menuUsuario.getContentPane().add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 100));

        jButton12.setText("comprar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        menuUsuario.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Need For Speed");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        CrearCuenta.setBackground(new java.awt.Color(153, 153, 153));
        CrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
        CrearCuenta.setText("Crear Cuenta");
        CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCuentaMouseClicked(evt);
            }
        });
        CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaActionPerformed(evt);
            }
        });

        IniciarSesionAdmin.setBackground(new java.awt.Color(153, 153, 153));
        IniciarSesionAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IniciarSesionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionAdmin.setText("Iniciar Sesion Admin");
        IniciarSesionAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionAdminMouseClicked(evt);
            }
        });
        IniciarSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionAdminActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(usuario);

        jScrollPane4.setViewportView(contraseña);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Correo");

        jScrollPane1.setViewportView(correo);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pais de Residencia");

        jScrollPane2.setViewportView(residencia);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de nacimiento");

        jScrollPane5.setViewportView(nacimiento);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");

        jScrollPane6.setViewportView(veriUsua);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario");

        jScrollPane7.setViewportView(veriContra);

        jButton8.setText("ingresar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(210, 210, 210)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(IniciarSesionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 27, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addGap(10, 10, 10)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel8)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jLabel7)
                            .addGap(0, 0, 0)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(IniciarSesionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCuentaMouseClicked
        Usuario obj;
        obj = new Usuario(usuario.getText(), contraseña.getText(), correo.getText(), residencia.getText(), nacimiento.getText());
        datos.add(obj);

        usuario.setText("");
        contraseña.setText("");
        correo.setText("");
        residencia.setText("");
        nacimiento.setText("");

    }//GEN-LAST:event_CrearCuentaMouseClicked

    private void CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaActionPerformed

    private void IniciarSesionAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionAdminMouseClicked
        if (veriContra.getText().equals("admin")) {
            menu.setVisible(true);
            menu.pack();
            menu.setLocationRelativeTo(this);
            
        } else {
            javax.swing.JOptionPane.showInputDialog("Contraseña Incorrecta");
        }

    }//GEN-LAST:event_IniciarSesionAdminMouseClicked

    private void IniciarSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSesionAdminActionPerformed

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        tunear.setVisible(true);
        tunear.pack();
        tunear.setLocationRelativeTo(this);
        menu.setVisible(false);
    }//GEN-LAST:event_modificarMouseClicked

    private void EliminarAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAutoMouseClicked

        eliminar.setVisible(true);
        eliminar.pack();
        eliminar.setLocationRelativeTo(this);
        menu.setVisible(false);
    }//GEN-LAST:event_EliminarAutoMouseClicked

    private void EliminarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarAutoActionPerformed

    private void MostrarAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAutoMouseClicked

        mostrar.setVisible(true);
        mostrar.pack();
        mostrar.setLocationRelativeTo(this);
        menu.setVisible(false);
    }//GEN-LAST:event_MostrarAutoMouseClicked

    private void AgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAutoActionPerformed

    }//GEN-LAST:event_AgregarAutoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Auto nuevoAuto = new Auto(marca.getText(), modelo.getText(), color.getBackground(), Integer.parseInt(precio.getText()), origen.getText());
        auto.add(nuevoAuto);
        marca.setText("");
        modelo.setText("");
        precio.setText("");
        origen.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMouseClicked
        color.setBackground(JColorChooser.showDialog(this, "Seleccione color", Color.yellow));
    }//GEN-LAST:event_colorMouseClicked

    private void AgregarAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarAutoMouseClicked
        agregar.setVisible(true);
        agregar.pack();
        agregar.setLocationRelativeTo(this);
        menu.setVisible(false);
    }//GEN-LAST:event_AgregarAutoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        for (Auto y : auto) {
            if (buscar2.getText().equals(y.getModelo())) {
                y.setMarca(marca1.getText());
                y.setModelo(modelo1.getText());
                y.setPrecio(Integer.parseInt(precio1.getText()));
                y.setOrigen(origen1.getText());
            }
        }
        marca.setText("");
        modelo.setText("");
        precio.setText("");
        origen.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void color1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1MouseClicked
        color.setBackground(JColorChooser.showDialog(this, "Seleccione color", Color.yellow));
    }//GEN-LAST:event_color1MouseClicked

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(this);
        agregar.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(this);
        tunear.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        for (Auto t : auto) {
            if (buscar.getText().equals(t.getModelo())) {
                mos.setText(t.toString());
            }
        }


    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(this);
        mostrar.setVisible(false);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
    
        for (Auto a : auto) {
            if (buscar1.getText().equals(a.getModelo())) {
                auto.remove(a);
            }
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void busMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busMouseClicked
        for (Auto t : auto) {
            if (buscar1.getText().equals(t.getModelo())) {
                mos1.setText(t.toString());
            }
        }


    }//GEN-LAST:event_busMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(this);
        eliminar.setVisible(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        for (Auto b : auto) {
            if (buscar2.getText().equals(b.getModelo())) {
                car.setText(b.toString());
            }
            
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        secion.setVisible(true);
        secion.pack();
        secion.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        for (Usuario dt : datos) {
            if (contra.getText().equals(dt.getContraseña())) {
                menuUsuario.setVisible(true);
                menuUsuario.pack();
                menuUsuario.setLocationRelativeTo(this);
               
            }else{
                JOptionPane.showMessageDialog(null, "Contaseña Incorrecta");
            }
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        for (Auto b : auto) {
            if (cmp.getText().equals(b.getModelo())) {
                mt.setText(b.toString());
            }
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        JOptionPane.showMessageDialog(null, "Auto Comprado");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAuto;
    private javax.swing.JButton CrearCuenta;
    private javax.swing.JButton EliminarAuto;
    private javax.swing.JButton IniciarSesionAdmin;
    private javax.swing.JButton MostrarAuto;
    private javax.swing.JDialog agregar;
    private javax.swing.JButton bus;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField buscar1;
    private javax.swing.JTextField buscar2;
    private javax.swing.JTextArea car;
    private javax.swing.JTextField cmp;
    private javax.swing.JButton color;
    private javax.swing.JButton color1;
    private javax.swing.JTextField contra;
    private javax.swing.JTextPane contraseña;
    private javax.swing.JTextPane correo;
    private javax.swing.JDialog eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane marca;
    private javax.swing.JTextPane marca1;
    private javax.swing.JDialog menu;
    private javax.swing.JDialog menuUsuario;
    private javax.swing.JTextPane modelo;
    private javax.swing.JTextPane modelo1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextArea mos;
    private javax.swing.JTextArea mos1;
    private javax.swing.JDialog mostrar;
    private javax.swing.JTextArea mt;
    private javax.swing.JTextPane nacimiento;
    private javax.swing.JTextPane origen;
    private javax.swing.JTextPane origen1;
    private javax.swing.JTextPane precio;
    private javax.swing.JTextPane precio1;
    private javax.swing.JButton regresar;
    private javax.swing.JTextPane residencia;
    private javax.swing.JDialog secion;
    private javax.swing.JDialog tunear;
    private javax.swing.JTextPane usuario;
    private javax.swing.JTextPane veriContra;
    private javax.swing.JTextPane veriUsua;
    // End of variables declaration//GEN-END:variables
ArrayList<Auto> auto = new ArrayList();
    ArrayList<Usuario> datos = new ArrayList();
}
